name: fast_image
description: A fast image processing package.
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  code_assets: ^0.19.9
  ffi: ^2.1.4
  hooks: ^0.20.4
  native_toolchain_rs: ^0.1.2+3
  crypto: ^3.0.7

dev_dependencies:
  ffigen: ^19.1.0
  lints: ^6.0.0
  test: ^1.25.6
