name: fast_image_workspace
description: A workspace for the fast_image package.

environment:
  sdk: ^3.10.8

workspace:
  - fast_image
  - benchmarks
  # - upscale_flutter

hooks:
  user_defines:
    fast_image:
      local_build: true
